### ISSUE TITLE
put data/favicons in config

### ISSUE THREAD

**Issue by nzasch** [SSilence/selfoss#1042]
Hi,
I'm using selfoss for mass hosting: I set a different sqlite db path for each user and all is working well.
except that... as the data/favicons folder is shared, the cleanout routine is wiping all favicons as it didnt recognize the other users favicon....
is it possible to put data/favicons (or the entire data/ tree) in config?

thank you for selfoss, it's fantastic!

**Comment by jtojnar** [comment]
Customizable location of the data directory is actually something I want myself, as NixOS stores applications in write-protected directory by default.

The issue is somewhat more complex since it affects both selfoss and the HTTP server. selfoss needs to know the path where it can store the image files and the HTTP server needs to forward the URLs starting with `/favicons/` to the path.

I intend to redesign the directory structure (see https://github.com/SSilence/selfoss/issues/913) but this split makes it difficult. Perhaps we could ditch serving the favicons directly by the web server and route them in PHP instead, for most instances the bottleneck would probably not matter.

----

If you want to customize the paths, you will need to modify the content loader:

https://github.com/SSilence/selfoss/blob/a2763a82d8a472e3a95627177705de1b75ad632c/helpers/ContentLoader.php#L342

plus the clean-up routine:

https://github.com/SSilence/selfoss/blob/a2763a82d8a472e3a95627177705de1b75ad632c/helpers/ContentLoader.php#L446

and finally the `.htaccess`

https://github.com/SSilence/selfoss/blob/a2763a82d8a472e3a95627177705de1b75ad632c/.htaccess#L10

or the corresponding section of your configuration if you use a different web server.

**Comment by jtojnar** [comment]
Could you check if https://github.com/SSilence/selfoss/pull/1043 works for you?

**Comment by nzasch** [comment]
sorry for the delay
#1043 is ok for me!
thanks
