### ISSUE TITLE
items_lifetime parameter not working

### ISSUE THREAD

**Issue by nalljr** [SSilence/selfoss#1100]
I have selfoss (v2.18) installed using GoDaddy cPanel, and it seems the "item_lifetime" parameter is not deleting old items.  
1. Is there anyway to trigger it via cron (like the curl "update")?

**Comment by jtojnar** [comment]
Are you sure you are using `items_lifetime` instead of `item_lifetime`, you are mentioning in the post?

Clean up happens whenever a source is checked for updates so running `cliupdate.php` by cron will do.

**Comment by nalljr** [comment]
Apologies on the typo - it is "item**s**_lifetime".  But old items are still not being removed even after running "cliupdate.php".

Some stupid questions about "items_lifetime" parameter - "days until items will be deleted (marked items will never be deleted)".
1. Does "marked items" means "mark as read", "mark as unread", and "starred"?
2. How do you "unmark" an item?

PS: I know you can remove the items from the database directly, but I would rather have SelfOSS do it as configured.

**Comment by jtojnar** [comment]
It refers to starred items. Unstarred items will be removed if they they were last seen in the feed over `items_lifetime` days ago.

**Comment by nalljr** [comment]
I have go through the installation instructions (found that godaddy cpanel/installatron uses 755 directory permission for selfoss).
1. Permission for data/, data/*, and public/ directories have been updated it to "766".
2. Confirmed item records in sqlite have datetime column defined.
3. Checked error_log file (no error found).

Old items are still not deleted.

**Comment by jtojnar** [comment]
Note that the items cannot be removed while they are still in the feed – they would be added on the next update again, their state forgotten.

That is why selfoss tracks the last time it saw the post in the feed (`lastseen` column in the database). 

For example, let's assume we update selfoss once a day and `items_lifetime` is 5 days:

* Website shows posts from last 30 days in its feed: A post appears in selfoss on day 0 and website will remove it from the feed on day 30 – that will be the final `lastseen` date. On day 35, the post will exceed the lifetime and will be finally removed from selfoss.
* Social network shows last 50 posts: Similar to the situation above but instead of starting to count the lifetime after 30 days, it has to wait for 50 new posts to appear.
* A simple weblog shows all published posts in its feed: The post will never be removed.

**Comment by nalljr** [comment]
Thanks, that explains a lot on how selfoss maintains items.
