### ISSUE TITLE
[development branch] config / defaults.ini

### ISSUE THREAD

**Issue by herrxyz** [SSilence/selfoss#1106]
in last development "releases" (2.19-5c5beba andsome versions before) there is a defaults.ini in zip file.
updating my selfoss-instance, I need a config.ini also (which is not in zip file)
I copied defaults.ini to config.ini and use both files (with same content)
if I rename one of them, no matter which one, I only get a error message "An error occurred"

**Comment by jtojnar** [comment]
`defaults.ini` was always required and was not supposed to be modified (though selfoss does not care if you did so). User is supposed to create a `config.ini` and override each configuration key they care about. If a configuration key is not found in `config.ini` or the file does not exist, a value from `defaults.ini` is used.

https://github.com/SSilence/selfoss/blob/5c5bebaa1fd7ee1035785cb53450f9c98a003b1c/common.php#L26-L31

Selfoss packages intentionally omit `config.ini` so that users do not accidentally overwrite their configuration when upgrading.

Could you try changing the following line from `0` to 1`? That should give you more information about the nature of the error.

https://github.com/SSilence/selfoss/blob/5c5bebaa1fd7ee1035785cb53450f9c98a003b1c/common.php#L17

**Comment by herrxyz** [comment]
you are right with your qoute from common.php line 26-31, it's the same in mine and therefore there should be no problem
nevertheless, I recieve a error-message if 1 rename one of this files

with debug = 1
when config.ini renamed:
An error occurred: Missing file “config.ini”. Did you install the dependencies using npm? [/var/www/vhosts/XXX.de/httpdocs/selfoss/helpers/View.php:152] [selfoss/helpers/View.php:275] helpers\View::maxmtime() [selfoss/helpers/View.php:285] helpers\View::offlineMtime() [selfoss/helpers/View.php:34] helpers\View->genOfflineSW() [selfoss/controllers/BaseController.php:22] helpers\View->__construct() [selfoss/vendor/bcosca/fatfree-core/base.php:1826] ReflectionClass->newInstanceArgs() [selfoss/vendor/bcosca/fatfree-core/base.php:1847] Base->grab() [selfoss/vendor/bcosca/fatfree-core/base.php:1676] Base->call() [selfoss/index.php:81] Base->run()

when defaults.ini renamed:
An error occurred: Missing file “defaults.ini”. Did you install the dependencies using npm? [/var/www/vhosts/XXX.de/httpdocs/selfoss/helpers/View.php:152] [selfoss/helpers/View.php:275] helpers\View::maxmtime() [selfoss/helpers/View.php:285] helpers\View::offlineMtime() [selfoss/helpers/View.php:34] helpers\View->genOfflineSW() [selfoss/controllers/BaseController.php:22] helpers\View->__construct() [selfoss/vendor/bcosca/fatfree-core/base.php:1826] ReflectionClass->newInstanceArgs() [selfoss/vendor/bcosca/fatfree-core/base.php:1847] Base->grab() [selfoss/vendor/bcosca/fatfree-core/base.php:1676] Base->call() [selfoss/index.php:81] Base->run()

**Comment by jtojnar** [comment]
Hmm, you are right. I did not realize that our offline mode changes made the `config.ini` file mandatory.

https://github.com/SSilence/selfoss/blob/5c5bebaa1fd7ee1035785cb53450f9c98a003b1c/helpers/View.php#L269-L270

I guess this is a regression, thanks for reporting. Fixed in 8afb1a2.
