### ISSUE TITLE
feeds from "Github releases" not shown

### ISSUE THREAD

**Issue by Offerel** [SSilence/selfoss#1110]
If i add a feed from Github releases, no updates are displayed. For example i try to get updates for https://github.com/PhilippC/keepass2android/releases.atom, nothing seems to be updated. I didnt see any error in the logfile.

The is also a "Github" type for feeds, but i have no idea, how to use this for only a release feed.

**Comment by jtojnar** [comment]
How did you try to update the feed? Just adding a source does not trigger an immediate update. You either: need to press the refresh button in the sidebar to refresh all sources, press “Refresh this source” when you open the specific source in the sidebar, or trigger the `cliupdate.php` (for example by cron).

GitHub spout is just for commits. In the future, I would like to remove it since GitHub still supports RSS so the spout is redundant.

**Comment by Offerel** [comment]
No, i use a cronjob: `crontab -e -u www-data`

`*/22 * * * * php /var/www/freshrss/app/actualize_script.php > /var/log/FreshRSS.log 2>&1`

**Comment by jtojnar** [comment]
Yeah, you are right. Selfoss clears all items older than `items_lifetime` days. You can change the number in `config.ini`.

**Comment by Offerel** [comment]
Thx for that info. Then i wait for some new release. I love the project so far. It's so much faster than tt-rss. specially on a Raspberry Pi.
