### ISSUE TITLE
Update Lighttpd Wiki

### ISSUE THREAD

**Issue by dgsiegel** [SSilence/selfoss#1175]
With recent changes, the following two lines would have to be added and/or merged with existing lines:

```
      "^/(user.(js|css))(\?.*)?$" => "/$1",
      "^/([^\?]*.(js|ico|gif|jpg|png|css|asc|txt|eot|woff|woff2|ttf|svg|map))(\?.*)?$" => "/public/$1",
```
The first one allows `user.js/css` to be found and included. The second one adds a `map` extensions, which is requested by most browser development tools.

**Comment by jtojnar** [comment]
Hopefully fixed in

* https://github.com/SSilence/selfoss/wiki/Lighttpd-configuration/_compare/aecf053e791dd8accfc1cd0474fce588998ed6fc...6c2de7aad4f9995b5ea0d1d4417ac634d163c8d3
* https://github.com/SSilence/selfoss/wiki/Installing-on-Raspberry-Pi-with-lighttpd/_compare/247037a24d3a5eb02b89d60144ffce8ccda386da...9a14320597440e9a9c65aff5f69282214526a184

Thanks for reporting.

**Comment by ziegenberg** [comment]
I guess this an be closed now since it's fixed...
