### ISSUE TITLE
Bintray offers galactic zip files only

### ISSUE THREAD

**Issue by theAkito** [SSilence/selfoss#1179]
So after hours of frustration I came to the root of the problem at hand.
I was trying to get and successfully extract a zip from [Bintray](https://bintray.com/fossar/selfoss/selfoss-git/2.19-1e1e15c#files).
The file is:
```
selfoss.zip: Zip archive data, at least v6.3 to extract
```

But NO distribution I checked uses an `unzip` version above 6.0.x .
Not even Edge repositories, that deliver the newest packages...
I checked

* Alpine Edge
* Debian Sid
* Ubuntu Focal

Therefore, the zip file is quite useless for Linux users.
A possible solution would be to additionally distribute `.tar.xz` files.

**Comment by jtojnar** [comment]
Interesting. I can extract it using file-roller but perhaps it prefers libarchive backend.

I guess the upgrade was caused by the recent rewrite of the archive generator https://github.com/SSilence/selfoss/blob/master/utils/create-zipball.py.

I will try to downgrade it and test it with different unpackers when I have time but will probably add `xz` or `zstd` compressed tarball as well. (Even though the LZMA-compressed zips are much better than before the rewrite.)

For now you can try to unpack it using p7zip’s `7z x selfoss-2.19-f0759b2.zip` command or libarchive’s `bsdtar -f selfoss-2.19-f0759b2.zip -x`.

Thanks for reporting.

**Comment by theAkito** [comment]
Indeed, the following works:

```
apt install -y p7zip-full
7z x selfoss.zip
```

**Comment by jtojnar** [comment]
This should be now fixed. Tested with `unzip` `7z` and `bsdtar`. Thanks again for bringing this to my attention.

**Comment by theAkito** [comment]
Can confirm!
```
selfoss.zip: Zip archive data, at least v2.0 to extract
```
Tested and works with e.g.:
```
zip --version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
```
Thank you!
