### ISSUE TITLE
Feed icon replacing icon from different feeds

### ISSUE THREAD

**Issue by sonicnkt** [SSilence/selfoss#1189]
With the latest snapshot (selfoss-2.19-5661343.zip) i noticed that one feed that has an embedded feed logo (Gamestar.de) replaced the icon of other feeds as well. You can see this in the normal article list as well as the sources window. 

I am not sure if this is related to the feed having an embedded logo but currently only that icon on my setup is "taking over" the other ones. 

I mentioned this  briefly in https://github.com/SSilence/selfoss/issues/1186  but since it still happens with the latest snapshot for me i opend a new issue.

I have modified fulltextrss.php like mentioned here https://github.com/SSilence/selfoss/issues/1114#issuecomment-511080224 to get thumbnails for all those feeds, but i cant image this being ralted to that.

Here are some screenshots of the issue:
![selfoss-icon-issue_1](https://user-images.githubusercontent.com/5454622/80989123-c901bf80-8e34-11ea-8389-5d17484692eb.jpg)

![selfoss-icon-issue_2](https://user-images.githubusercontent.com/5454622/80989137-cf903700-8e34-11ea-81bb-2a60f8fd3a8d.jpg)

Before submitting this i noticed that a few minutes later another icon took over another feed:

![selfoss-icon-issue_3](https://user-images.githubusercontent.com/5454622/80989163-d4ed8180-8e34-11ea-82ef-ddaa3a1c8bba.jpg)

Anyone experiencing the same issue?

**Comment by jtojnar** [comment]
Thanks for reporting.

Bisection pointed to this change 87a63aae4e3001d576f34d3df1cae7896cde806f. Apparently, we created a new `SpoutLoader` for every spout we updated because it could only create a single instance of spout. The commit that broke things switched to creating a single `SpoutLoader`. It is nice how these refactors reveal broken assumptions from years ago.
