### ISSUE TITLE
Have update page redirect to home once all udpates are done

### ISSUE THREAD

**Issue by Riduidel** [SSilence/selfoss#172]
Each time i want to see my feeds, I start by typing http://my.server.is.not.secure.enough/selfoss/update to have streams updated, then I have to go back to http://my.server.is.not.secure.enough/selfoss/ to view the updated content. Couldn't it be possible for update to redirect (http way or any  other convenient one) to home once it's done ?

**Comment by thatscoteng** [comment]
Considering there is now a refresh button on the main page, is this still wanted/required?

**Comment by Spy-Seth** [comment]
Yes this script is mandatory to allow automatic update through crontab.

**Comment by thatscoteng** [comment]
Just noticed this issue is still open.
My previous question, what I meant was - is the redirect sitll wanted/required (I know the main page itself is).

Before the refresh button was added, I had modified my version to include a bit of JavaScript on the refresh page to redirect to the main page. (I chose JavaScript to avoid interfering with ajax/cron updates)

If this feature is still wanted, I could open a pull request with what I did. Otherwise this issue can be closed.
