### ISSUE TITLE
[Request] Width of navigation bar

### ISSUE THREAD

**Issue by icymist** [SSilence/selfoss#620]
Can the width of the navigation bar be increased on the desktop version? If yes, how? If not, can you make it a customizable option?

**Comment by alfredbuehler** [comment]
+1 for this request.

**Comment by niol** [comment]
From a quick glance, in ```public/css/style.css```, there are some elements to change:
- ```#nav { width: 180px; }```
- ```#content { margin-left: 220px; }```
- maybe ```#search-list { margin-left: 220px; }```

Increasing those values should do it, but this should be done only for the desktop version, so within the ```@media screen and (min-width: 1024px)``` block.

But first, and regarding a configurable option, here are a few ideas on how to address this request:
  1. navigation bar could be sized in % of screen width instead of pixels.
  1. it could be an option in config.ini : width of nav bar in pixels or %.
  1. it could be resizable by draging the separator, and saving the value in the session cookie
  1. it could be resizable by draging the separator, and saving the value in the database (though there is nothing yet in selfoss to save conf in db)

What do you people think?

**Comment by alfredbuehler** [comment]
I vote for #3, would be fine for me.

**Comment by jcbrand** [comment]
I would propose a variation of 3.

Instead of saving in the session cookie, save it in the browser's localStorage.

Two advantages:
* you don't bloat your request by adding stuff in cookies that is not needed server-side
* localStorage persists across sessions

You can prefix the storage key with the user's username to keep it confined to the user who made the change.

**Comment by jtojnar** [comment]
This can be done in `user.css`.
