### ISSUE TITLE
YouTube sprout will stop working in May

### ISSUE THREAD

**Issue by gerundt** [SSilence/selfoss#640]
I got today a warning video in a YouTube sprout, that the old API will drop:

> In early May, Data API v2 video calls will start returning only the warning video introduced on April 20. Users will not be able to view other videos on apps that use the v2 API video calls. See youtube.com/devicesupport for affected devices.
> 
> By late May, v2 API calls except for comments and captions will receive 410 Gone HTTP responses.

http://youtube-eng.blogspot.de/2015/04/bye-bye-youtube-data-api-v2.html

**Comment by ochristi** [comment]
Hi, noticed this too. I got a working fix, but would need a solution to avoid duplicates.
The old spout used to insert uid for items in the form of "`http://gdata.youtube.com/feeds/api/videos/{videoid}`", now I would get uid in the form of "`yt:video:{videoid}`". Now it would insert all loaded items again, since the uid differ.
We could solve it by updating all old entries to follow the new format, but since it is a change in the spout and we do not have "versions" for that, I have the following idea:
* apply the compatibly fix to a new spout called `youtubev3`
* alter the original spout in a way, which will update the uids of all items of a source with the current spout path `spouts\youtube\youtube`
* this will update the path to `spouts\youtube\youtubev3`, but perform all other things as expected, e.g. by having `youtube` extend `youtubev3`
* next time the update will trigger the new path, which does not have to update the items again

Any suggestions, questions? (I hope I have my terminology clear.)

**Comment by PhrozenByte** [comment]
A straightforward solution would be something like this ([daos/mysql/Database.php](https://github.com/SSilence/selfoss/blob/master/daos/mysql/Database.php)), solutions for pgsql and sqlite would be quiet similar. Spouts aren't managed separately, they are updated with a new selfoss release; whether the source code changed or the database scheme.
```php
if(strnatcmp($version, "7") < 0){
    \F3::get('db')->exec('
        UPDATE items
        SET uid = REPLACE(uid, 'http://gdata.youtube.com/feeds/api/videos/', 'yt:video:')
        WHERE source IN (SELECT id FROM sources WHERE spout = 'spouts\\youtube\\youtube')
    ');
}
```

**Comment by niol** [comment]
Maybe you can abstract the uid compare function: make it a simple comparison for all spouts, and make it compare both forms of the uid for the youtube spout.

If you can avoid a databse schema version, it's better, because it's 3 times the work and the tests.

**Comment by ochristi** [comment]
I think I will go with the compare thingy, just stripping the stuff before in the process and leaving the plain video id.
```php
$id = str_replace(
	array('http://gdata.youtube.com/feeds/api/videos/', 'yt:video:'),
	"",
	$id
);
```

**Comment by ochristi** [comment]
Well, this attempt to customize the `getId()` function of the youtube spout does not work, as it is only compared to the already present `uid` of items in the DB, which are all starting with `http://gdata.youtube.com/feeds/api/videos/`.
I do not want to touch the following part of [helpers/ContentLoader.php](https://github.com/SSilence/selfoss/blob/master/helpers/ContentLoader.php) and bloat the comparison which will probably only yield many complications.
```php
if (isset($itemsFound[$item->getId()])) {
    continue;
}
```
The least intrusive approach would be to just replace `yt:video:` with the old prefix, but I am not too happy with such a solution.

**Comment by gerundt** [comment]
I use now this RSS feed URLs instead of the sprout:

* https://www.youtube.com/feeds/videos.xml?channel_id=CHANNELID
* https://www.youtube.com/feeds/videos.xml?user=USERNAME

[Source: www.reddit.com](https://www.reddit.com/r/youtube/comments/339idg/youtube_just_dropped_its_support_for_rssatom_feeds)

**Comment by ochristi** [comment]
That is what I changed the spout to. I have not yet managed to create a pull request. I also wanted to add an option for channels with id only.

**Comment by vegbrasil** [comment]
Any progress on updating the spout? Or migrating to RSS is the only way?
