### ISSUE TITLE
Cookie URLs aren't build correctly

### ISSUE THREAD

**Issue by fabsh** [SSilence/selfoss#756]
As soon as I turn on login via username/password I can't get to the main selfoss page anymore. Turning on DEBUG gives the message that I am logged in but then I it reports the session isn't valid. Looking at the generated cookie, I figured out that the cookie domain is _subdomain.domain.com_ and the path is _subdomain.domain.com_ -- this is obviously wrong. I patched this by hardcoding my domain to _subdomain.domain.com_ and the path to _/_ in Authentication.php like this:

```
// check for SSL proxy and special cookie options
        if(isset($_SERVER['HTTP_X_FORWARDED_SERVER']) && isset($_SERVER['HTTP_X_FORWARDED_HOST'])
           && ($_SERVER['HTTP_X_FORWARDED_SERVER']===$_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $cookie_path = '/';
            $cookie_domain = 'subdomain.domain.com';
        } else {
            // cookie path is script dir.
            $cookie_path = '/';
            $cookie_domain = 'subdomain.domain.com';
        }
```

Now authentication works but this is obviously very ugly. I'm running on a Webfaction vserver. I'm guessing the $_SERVER variables are messed up somehow but know to little to know how exactly that is broken and why.

**Comment by doucheymcdoucherson** [comment]
The above fix worked for me. Having the same problem. I was not getting redirected when logging into the page. Using nginx frontend to redirect to apache backend.

**Comment by lost-geographer** [comment]
I had the same problem as @fabsh and @doucheymcdoucherson, but my workaround is different : I just removed some code from Authentication.php at line 37. This is the old line:

`$cookie_path = '/'.$_SERVER['SERVER_NAME'].preg_replace('/\/[^\/]+$/','',$_SERVER['PHP_SELF']).'/';`

And this is the new one:

`$cookie_path = preg_replace('/\/[^\/]+$/','',$_SERVER['PHP_SELF']).'/';`

The $_SERVER['SERVER_NAME'] in $cookie_path variable makes the same result as $cookie_domain (at line 38). With the old code, the server returned this results :

`$cookie_path = /domain.com/path/`
`$cookie_domain = domain.com`

As the cookie's url is build from $cookie_domain + $cookie_path, you'll get an invalid address because of the duplicated server name. In the DEBUG log you can see something like this :

`set cookie on domain.com/domain.com/path/ expiring in 2592000 seconds`

I don't fully understand how the $cookie_path variable is used, but with this little workaround the problem seems to be solved.

**Comment by jtojnar** [comment]
Does #766 fix your problem?

**Comment by lost-geographer** [comment]
@jtojnar No. I suppose that #766 didn't work because it changes URL building rules only in case of a normal http connection. This problem occurs in case of an https or proxy connection.

However, i think your idea is good: it may allow Selfoss to get rid of the protocol verification in Autentication.php and View.php...
