### ISSUE TITLE
Old rss messages

### ISSUE THREAD

**Issue by UnamedRus** [SSilence/selfoss#784]
There any chance to import old rss messages(created before adding new source to selfoss) to selfoss?

**Comment by jtojnar** [comment]
From where would you like to import them?

If you have an older copy of the feed you could set it as spout source and load the items. Otherwise you would need to scrape the website and create your own feed (or possibly add the scraped messages directly to the database).

**Comment by UnamedRus** [comment]
I have 2 choices:Rss feed or Tumblr user. 
After adding as source ~import week old posts. Well will try scrape down site. 
Create own feed=>add to selfoss=>duplicate old posts to own feed=>selfoss will catch them. Did you mean this?
Or directly intervention in databese.
Thx for answer

**Comment by jtojnar** [comment]
Yes, I meant this:

1. Create your own feed with the old items
2. Add a new RSS spout with this feed as an URL (in settings)
3. Update the sources
4. Now the old items will be in one of your sources
5. Change the spout URL to the real feed
6. Now if new items are released, they will appear in the same feed

It is important to change the source URL instead of creating a new source so the items are added to the same source.

If there are any items both in your old feed and the current feed they will be added only once, as long as the items have the same URL/guid.

Also note that selfoss removes the items after a certain period of time from the time they were loaded to selfoss (30 days by default, configured by `items_lifetime`).
