### ISSUE TITLE
Vacuum is not an optimization

### ISSUE THREAD

**Issue by sanpii** [SSilence/selfoss#888]
Hello,

The [`optimize`](https://github.com/SSilence/selfoss/blob/master/daos/pgsql/Database.php#L216-L229) method for postgresql (and probably for sqlite) is not an optimization, it’s a performance trap.

![2017-03-09-202148_1676x993_scrot](https://cloud.githubusercontent.com/assets/113045/23766945/0170e130-0507-11e7-8715-2231cc4904af.png)

There is already a daemon doing auto vacuum when it’s necessary.

**Comment by jtojnar** [comment]
From a brief scan of the documentation, it seems autovacuum is [optional](https://www.postgresql.org/docs/9.6/static/routine-vacuuming.html#AUTOVACUUM). Would [detecting](https://stackoverflow.com/questions/19826467/how-can-i-tell-if-postgresqls-autovacuum-is-running-on-unix) if autovacuum was ran any time in the previous month and starting manual vacuum otherwise be an acceptable solution?

**Comment by sanpii** [comment]
@jtojnar yes, it’s could be a good compromise.

For me vacuum is a dba problem, but if selfoss made many insertion/deletion it maybe a good idea to compensate an omission.

**Comment by sanpii** [comment]
Yesterday, after talking to a postgresql expert, I discover that autovacuum is enabled by default:

>  In the default configuration, autovacuuming is enabled and the related configuration parameters are appropriately set.

If someone disable it, he knows what he’s doing, it’s not a good idea to force vacuum.
