### ISSUE TITLE
commit #4ac4000 breaks existing lighttpd configuration  

### ISSUE THREAD

**Issue by dgsiegel** [SSilence/selfoss#910]
as with commit #4ac4000, js and css files are loaded with a query string and the [suggested lighttpd configuration](https://github.com/SSilence/selfoss/wiki/Lighttpd-configuration) will stop working. the issue is that the lighttpd rewrite engine will look at the full url with the querystring (e.g. /all.js?v=1234..) and therefore the regex pattern 

`
 "^/(.*.(js|ico|gif|jpg|png|css|asc|txt|eot|woff|ttf|svg))$" => "/public/$1",
`

will stop working. an easy fix would be to add the querystring after the regex, however i think using `url.rewrite-if-not-file` would be a better solution.

`
"^/(.*.(js|ico|gif|jpg|png|css|asc|txt|eot|woff|woff2|ttf|svg))(\?.*)?$" => "/public/$1",
`

**Comment by jtojnar** [comment]
Maybe even better would be removing these complex rewrite rules and just using `src="public/all.js"` in the client.

**Comment by jtojnar** [comment]
@niol what do you think about simplifying the rewrites?

**Comment by niol** [comment]
The point of query string cache busting is to avoid having bug reports because of the use of outdated js. I think this is important and also handy for upgrades and development.

If simplifying rewrite rules for lighttpd is wanted (no problem with apache), there is the previous implementation I proposed (using files with a timestamp in their name).

**Comment by jtojnar** [comment]
I was actually thinking about dropping the rewrite rules altogether and using the real path ($root/public/app.js) in the script tags. That should fix this problem and also simplify the installation – I remember someone wanting to install selfoss on Hiawatha web server and citing rewrite rules as obstacle.

**Comment by niol** [comment]
Yes, great, no objection to that. Also moving generated assets to ```public/gen``` or  ```data/gen``` would avoid giving too much permissions to the user running php.

**Comment by jtojnar** [comment]
@dgsiegel Since I do not know `url.rewrite-if-not-file`, I have updated the wiki page to use the improved regex, for now. I also updated the upgrade instructions. Additionally, if you can provide an example of `url.rewrite-if-not-file`, I will be thankful if you edit the wiki.

@niol I wrote down some ideas in #913, please try to check if I missed something.

P.S. I will also be available on the [gitter chat](https://gitter.im/fossar/selfoss).

**Comment by dgsiegel** [comment]
@jtojnar `url.rewrite-if-not-file` is similar to Apache´s "!-f" RewriteRule and unfortunately only works with actual, existing files. as most files are in the `/public` directory but being referred as `/` this approach won't work with the current state.
