### ISSUE TITLE
Hide "unread" in public read only view?

### ISSUE THREAD

**Issue by poVoq** [SSilence/selfoss#984]
Is there an option to hide the "unread" filter? I would like to do so especially in public view as it makes little sense there.

Alternatively, is there a way to have it work with non-logged in users, maybe through a cookie or so?

**Comment by jtojnar** [comment]
1. You can create `user.css` file in the root directory and add the following code there:

```css
body:not(.loggedin) #nav-filter-unread {
    display: none;
}
```

2. Do you mean like multi-user support where each visitor would store the articles she read in her browser? We want to add multi-user support but I did not yet think about the specifics. We also have a proof of concept of storing the information in the browser but is only designed to mirror the server state.

Would it be acceptable for your users to register an account to be able to store read state?

**Comment by poVoq** [comment]
The CSS trick should do for me. Thanks.

I honestly wouldn't waste my time on multi-user. There are plenty of options like that (miniflux probably the best), and most people would probably preferred something tightly integrated anyways. So either have a bunch of integrations in popular email apps or nextcloud etc. or go a completely different way.

Personally I would focus more on public facing RSS aggregation services, as there isn't really a nice looking php planet like feed aggregator that is easy to install and works with sqlite.

I think most people just want a nice curated list of news with some very simple personalisation options (like bookmarking a link that has a filter for tags in it) and not bother with putting together their own feed aggregator.

If possible avoid registration alltogether and rather use in browser storage, cookies or something like that. Or just filters/tags that work as bookmarks as described above.

What could be nice also is adding federated microblogging feeds, so that you can follow for example Mastodon accounts. However I think they already support RSS feeds, so there should be some more functionality.

Notifications from matix.org channels could be also cool. Maybe the easiest for such could be some hook to a chatops bot like hubot or errbot?

**Comment by jtojnar** [comment]
Multi-user has long been on my to-do list – I want to provide selfoss to my family and currently it requires running multiple instances. Since I do not really want to reinvent the wheel of authentication I would either integrate with NextCloud or use something like LDAP. It will probably be a plug-in so people can use different authentication methods or even none.

As for the public facing aggregator, we develop selfoss for ourselves so we prioritize the features we want to use. Because I do not need public service, I have no idea what features it should have. If I tried to create one the result would probably not satisfy either of us. You are still free to request features or submit patches though.

I, for one, want to put together my own aggregator 😉

I will see what I can do about it, though selfoss is still primarily a server-based RSS reader.

Better integration with federated web services is definitely something I want to look into, just did not found time yet.

I agree that Matrix client would cool but unless there is a PHP library, it will not be feasible.

**Comment by poVoq** [comment]
The above user.css code is not working it seems.

**Comment by jtojnar** [comment]
@poVoq It works for me on 2.17 and master. Could you try deleting `public/all.css`?

**Comment by poVoq** [comment]
After deleting public/all-v2.17.css
it seems to work.
