### ISSUE TITLE
News content: table content overlap text

### ISSUE THREAD

**Issue by Binnette** [SSilence/selfoss#999]
Hi,

Can you please fix this bug ? Here you can see that there is a table. And its content overlap the text of the third column in selfoss web App.
![2017-11-27 21_39_50-selfoss 129](https://user-images.githubusercontent.com/6597721/33288364-4a8728be-d3bc-11e7-9651-b6d1dd84ddc9.png)

=How to reproduce =

1. Add a new feed with url
2. Select Type RSS Feed (with FullTextRss)
3. Url https://blogs.msdn.microsoft.com/dotnet/feed/
4. Get the feed named "Announcing the Windows Compatibility Pack for .NET Core". You can find the news here: https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/

=Versions =

- selfoss 2.17 (web app only)
- Mozilla Firefox 57.0 64bits

**Comment by Binnette** [comment]
Here is another one, not with a table but with a bullet list "< ul > < li > ..."
![2017-11-27 21_55_09-clipboard](https://user-images.githubusercontent.com/6597721/33288792-be4ec65c-d3bd-11e7-8662-56176c11087e.png)

I think the bug fix is gona be the same. So I don't want to create another issue... (And of course I'm a developper, so i'm lazzy 😅)

= How to reproduce =
Idem except the news is ".NET Framework November 2017 Security and Quality Rollup"
https://blogs.msdn.microsoft.com/dotnet/2017/11/14/net-framework-november-2017-security-and-quality-rollup/

**Comment by jtojnar** [comment]
I think there was a similar issue for `<pre>` tags but cannot find it at the moment. Anyway, I fixed it the same way (by adding `overflow-x: auto`). It works for the “Announcing the Windows Compatibility Pack for .NET Core” article but not for the “Introducing Tensor for multi-dimensional Machine Learning and AI data” because the table there specifies a width. I also updated the sanitizer to strip the width on new items.

As for the long word, `overflow-wrap: break-word` is a good solution.

You can test the changes in #1001.

**Comment by Binnette** [comment]
So I just apply the 1001.patch on my server :
`wget https://patch-diff.githubusercontent.com/raw/SSilence/selfoss/pull/1001.patch`
`patch -p1 < 1001.patch`

And I confirm, that your fix is working great 👍 

First article:
![2017-11-28 18_38_29-selfoss 97](https://user-images.githubusercontent.com/6597721/33334964-fb7f53bc-d46b-11e7-9953-67dc7e352dcf.png)

Second article:
![2017-11-28 18_40_02-selfoss 97](https://user-images.githubusercontent.com/6597721/33334967-fd72043a-d46b-11e7-9424-8a20c24abf43.png)

And as you said, there is still an issue on the article "Introducing Tensor for multi-dimensional Machine Learning and AI data"

For this kind of issue, can you please consider adding my following css code:
```
.entry-content > table[width] {
    width: auto;
}
```

This do the trick 😉 In fact my selector applies only on table with fixed width. And it enforce the fixed width to an "auto" width. 👌

Here is the result : 
![2017-11-28 19_01_19-selfoss 97](https://user-images.githubusercontent.com/6597721/33336064-16ae9244-d46f-11e7-8cdc-1c0ba0890eda.png)

**Comment by jtojnar** [comment]
The issue will only appear with old articles that had the tables with `width` attribute. If you were to remove the article from database and refresh the source (or remove the source and re-add it), it would behave correctly. Since the CSS rule only applies to articles with tables with width attribute fetched before this update, I would rather not complicate the styles further – I am sure we have plenty of dead code as is.
